Make building much easier and flexible
PolyMarsDev/Twini-Golf pull request #10
Opened 2021-08-14 21:08 UTC by TheRealKeto

This PR makes building the project much easier and flexible by using a Makefile. This way, a two-liner can be used in order to do all the work (rather than a long command with arguments).

The workflow was also changed in order to use the Makefile, and the new commands were reflected on the README. Specific changes have been documented in the commit message.

2021-08-18 02:24 UTC, TheRealKeto commented
I'm marking this as a draft since I realized that this can be done much better; once I implement those changes (and there are no PRs for the workflow), I will change the status of the PR.

2021-08-18 03:39 UTC, TheRealKeto commented
This is ready, just need to update compiling notes again; Linux and web builds compile successfully.

2021-08-19 17:16 UTC, mandar1jn requested changes

2021-08-19 17:16 UTC, mandar1jn commented on .github/workflows/build.yaml
> +  workflow_dispatch:
```suggestion
on: [push, pull_request, workflow_dispatch]
```
As the writer of the original workflow I would like to request this change. It's essentially the same, but only uses one line of code instead of 7.

2021-08-19 22:20 UTC, TheRealKeto commented on .github/workflows/build.yaml
> +  workflow_dispatch:
A specific PR (which disables the workflow for small commits, such as a README change) uses my current format, so it's not logical to simply use a list after that PR is merged.

2021-08-20 09:33 UTC, mandar1jn commented on .github/workflows/build.yaml
> +  workflow_dispatch:
Damn. I totally forgot. I wrote that PR. I didn't keep merge issues in mind while making this suggestion

2021-08-20 09:34 UTC, mandar1jn approved these changes
This should be merged. This makefile is very handy and as the author of the workflow I can say that this is way beter

2021-09-06 19:45 UTC, TheRealKeto commented
This is ready now. Everything is as fast as it will ever be. 

I managed to make the workflow cache emscripten so that it doesn't need to be setup every time (for the web-build). This increased the speed of the workflow after its first run.

2021-09-07 07:27 UTC, mandar1jn approved these changes

2023-12-04 19:36 UTC, closed without merging